package jef_puff;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amali
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class WilayahJakartaBarat extends javax.swing.JFrame {

private int[] idTempat = new int[5];
private JLabel[] labelNama;
private JLabel[] labelRating;
private JLabel[] labelLokasi;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WilayahJakartaBarat.class.getName());

    /**
     * Creates new form WilayahJakartaBarat
     */
    private String wilayah;
    
public WilayahJakartaBarat() {
    initComponents();

    labelNama = new JLabel[]{
        jLabelToko1, jLabelToko2, jLabelToko3, jLabelToko4, jLabelToko5
    };

    labelRating = new JLabel[]{
        jLabelRating1, jLabelRating2, jLabelRating3, jLabelRating4, jLabelRating5
    };

    labelLokasi = new JLabel[]{
        jLabelLokasi1, jLabelLokasi2, jLabelLokasi3, jLabelLokasi4, jLabelLokasi5
    };

    jButton8.setVisible(false);

    tampilkanDataTempat("Jakarta Barat");

    jButtonDetailToko2.addActionListener(e -> {
    Toko tk = new Toko(idTempat[1]);
    tk.setVisible(true);
    dispose();
    });
    
    jButtonDetailToko3.addActionListener(e -> {
    Toko tk = new Toko(idTempat[2]);
    tk.setVisible(true);
    dispose();
    });
}

private void tampilkanDataTempat(String wilayah) {
    jLabelWilayahTerpilih.setText(wilayah);

    String sql = "SELECT id_tempat, nama, rating, alamat FROM tempat WHERE wilayah = ? LIMIT 5";

    try {
        Connection conn = KoneksiDB.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, wilayah);

        ResultSet rs = pst.executeQuery();

        int i = 0;

        while (rs.next() && i < 5) {
            idTempat[i] = rs.getInt("id_tempat");

            labelNama[i].setText(rs.getString("nama"));
            labelRating[i].setText("⭐ " + rs.getString("rating"));
            labelLokasi[i].setText(rs.getString("alamat"));

            i++;
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }
}
 
private void tampilkanDetailPopup(int index) {
    String sql = "SELECT * FROM tempat WHERE id_tempat = ?";

    try {
        Connection conn = KoneksiDB.getConnection();
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setInt(1, idTempat[index]);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String detail =
                    "Nama Toko: " + rs.getString("nama") + "\n"
                    + "Rating: " + rs.getString("rating") + " (" + rs.getString("jumlah_ulasan") + " ulasan)\n"
                    + "Kategori: " + rs.getString("kategori") + "\n"
                    + "Alamat: " + rs.getString("alamat") + "\n"
                    + "Telepon: " + rs.getString("telepon") + "\n"
                    + "Jam Buka: " + rs.getString("jam_buka") + "\n\n"
                    + "Deskripsi:\n" + rs.getString("deskripsi");

            JOptionPane.showMessageDialog(this, detail, "Detail Toko", JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan detail: " + e.getMessage());
    }
}

    public WilayahJakartaBarat(String wilayah) {
    initComponents();
    this.wilayah = wilayah;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelRating1 = new javax.swing.JLabel();
        jLabelLokasi1 = new javax.swing.JLabel();
        jLabelToko1 = new javax.swing.JLabel();
        jLabelToko2 = new javax.swing.JLabel();
        jLabelRating2 = new javax.swing.JLabel();
        jLabelLokasi2 = new javax.swing.JLabel();
        jLabelToko3 = new javax.swing.JLabel();
        jLabelRating3 = new javax.swing.JLabel();
        jLabelLokasi3 = new javax.swing.JLabel();
        jLabelToko4 = new javax.swing.JLabel();
        jLabelRating4 = new javax.swing.JLabel();
        jLabelLokasi4 = new javax.swing.JLabel();
        jLabelToko5 = new javax.swing.JLabel();
        jLabelRating5 = new javax.swing.JLabel();
        jLabelLokasi5 = new javax.swing.JLabel();
        jButtonDetailToko1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelWilayahTerpilih = new javax.swing.JLabel();
        jButtonDetailToko2 = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonDetailToko3 = new javax.swing.JButton();
        jButtonDetailToko4 = new javax.swing.JButton();
        jButtonDetailToko5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 675));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRating1.setText("Rating");
        jPanel1.add(jLabelRating1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 156, 140, 20));

        jLabelLokasi1.setText("Lokasi");
        jPanel1.add(jLabelLokasi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabelToko1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelToko1.setText("nama toko");
        jPanel1.add(jLabelToko1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        jLabelToko2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelToko2.setText("Nama toko 2");
        jPanel1.add(jLabelToko2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabelRating2.setText("Rating");
        jPanel1.add(jLabelRating2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, 20));

        jLabelLokasi2.setText("Lokasi");
        jPanel1.add(jLabelLokasi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabelToko3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelToko3.setText("Nama toko");
        jPanel1.add(jLabelToko3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabelRating3.setText("Rating");
        jPanel1.add(jLabelRating3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLabelLokasi3.setText("Lokasi");
        jPanel1.add(jLabelLokasi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabelToko4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelToko4.setText("Nama toko");
        jPanel1.add(jLabelToko4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 280, 30));

        jLabelRating4.setText("Rating");
        jPanel1.add(jLabelRating4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        jLabelLokasi4.setText("Lokasi");
        jPanel1.add(jLabelLokasi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        jLabelToko5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelToko5.setText("Nama toko");
        jPanel1.add(jLabelToko5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, 20));

        jLabelRating5.setText("Rating");
        jPanel1.add(jLabelRating5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, -1, -1));

        jLabelLokasi5.setText("Lokasi");
        jPanel1.add(jLabelLokasi5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, -1, -1));

        jButtonDetailToko1.setBackground(new java.awt.Color(0, 153, 51));
        jButtonDetailToko1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDetailToko1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDetailToko1.setText("Detail");
        jButtonDetailToko1.addActionListener(this::jButtonDetailToko1ActionPerformed);
        jPanel1.add(jButtonDetailToko1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1002, 153, 130, 50));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Hasil Pencarian");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 20));

        jLabel21.setText("Menampilkan 5 hasil untuk  di wilayah");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 106, 210, 20));

        jLabelWilayahTerpilih.setText("nama wilayah");
        jPanel1.add(jLabelWilayahTerpilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 80, -1));

        jButtonDetailToko2.setBackground(new java.awt.Color(0, 153, 51));
        jButtonDetailToko2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDetailToko2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDetailToko2.setText("Detail");
        jButtonDetailToko2.setPreferredSize(new java.awt.Dimension(72, 23));
        jPanel1.add(jButtonDetailToko2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 263, 130, 50));

        jButtonBack.setText("<");
        jButtonBack.addActionListener(this::jButtonBackActionPerformed);
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, 70, -1));

        jButtonNext.setText(">");
        jPanel1.add(jButtonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, 70, -1));

        jButtonDetailToko3.setBackground(new java.awt.Color(0, 153, 51));
        jButtonDetailToko3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDetailToko3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDetailToko3.setText("Detail");
        jPanel1.add(jButtonDetailToko3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 373, 130, 50));

        jButtonDetailToko4.setBackground(new java.awt.Color(0, 153, 51));
        jButtonDetailToko4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDetailToko4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDetailToko4.setText("Detail");
        jButtonDetailToko4.addActionListener(this::jButtonDetailToko4ActionPerformed);
        jPanel1.add(jButtonDetailToko4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 480, 130, 50));

        jButtonDetailToko5.setBackground(new java.awt.Color(0, 153, 51));
        jButtonDetailToko5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDetailToko5.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDetailToko5.setText("Detail");
        jButtonDetailToko5.addActionListener(this::jButtonDetailToko5ActionPerformed);
        jPanel1.add(jButtonDetailToko5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1002, 583, 130, 50));

        jButton8.setBackground(new java.awt.Color(0, 153, 51));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Detail");
        jButton8.addActionListener(this::jButton8ActionPerformed);
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1002, 153, 130, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wilayahPerdaerah.jpg"))); // NOI18N
        jLabel17.setText("jLabel4");
        jLabel17.setPreferredSize(new java.awt.Dimension(1200, 675));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wilayahPerdaerah.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(1200, 675));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonDetailToko1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetailToko1ActionPerformed
    Toko tk = new Toko(idTempat[0]);
    tk.setVisible(true);
    dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDetailToko1ActionPerformed

    private void jButtonDetailToko5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetailToko5ActionPerformed
    Toko tk = new Toko(idTempat[4]);
    tk.setVisible(true);
    dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDetailToko5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonDetailToko4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetailToko4ActionPerformed
    Toko tk = new Toko(idTempat[3]);
    tk.setVisible(true);
    dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDetailToko4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WilayahJakartaBarat().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDetailToko1;
    private javax.swing.JButton jButtonDetailToko2;
    private javax.swing.JButton jButtonDetailToko3;
    private javax.swing.JButton jButtonDetailToko4;
    private javax.swing.JButton jButtonDetailToko5;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelLokasi1;
    private javax.swing.JLabel jLabelLokasi2;
    private javax.swing.JLabel jLabelLokasi3;
    private javax.swing.JLabel jLabelLokasi4;
    private javax.swing.JLabel jLabelLokasi5;
    private javax.swing.JLabel jLabelRating1;
    private javax.swing.JLabel jLabelRating2;
    private javax.swing.JLabel jLabelRating3;
    private javax.swing.JLabel jLabelRating4;
    private javax.swing.JLabel jLabelRating5;
    private javax.swing.JLabel jLabelToko1;
    private javax.swing.JLabel jLabelToko2;
    private javax.swing.JLabel jLabelToko3;
    private javax.swing.JLabel jLabelToko4;
    private javax.swing.JLabel jLabelToko5;
    private javax.swing.JLabel jLabelWilayahTerpilih;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
