package jef_puff;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amali
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

public class Booking extends javax.swing.JFrame implements BookingService{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Booking.class.getName());
    private int idBookingTerpilih = 0;

    /**
     * Creates new form Booking
     */
    public Booking() {
     
    initComponents();
    setLocationRelativeTo(null);
    setResizable(false);
    
    tampilDataTabel();
    }   
        public Booking(String namaToko,
               String layanan1,
               String layanan2,
               String layanan3,
               String tanggal,
               String jam,
               String keluhan) {

    initComponents();
    tampilDataTabel();
    
    
    jLabel7.setText(namaToko);


    jLabel4.setText(layanan1);
    jLabel5.setText(layanan2);
    jLabel6.setText(layanan3);

  
    jComboBoxJam.removeAllItems();
    
    jComboBoxJam.addItem("08:00 - 09:00");
    jComboBoxJam.addItem("09:00 - 10:00");
    jComboBoxJam.addItem("10:00 - 11:00");
    jComboBoxJam.addItem("11:00 - 12:00");
    jComboBoxJam.addItem("12:00 - 13:00");
    jComboBoxJam.addItem("13:00 - 14:00");
    jComboBoxJam.addItem("14:00 - 15:00");
    jComboBoxJam.addItem("15:00 - 16:00");
    jComboBoxJam.addItem("16:00 - 17:00");
    jComboBoxJam.addItem("17:00 - 18:00");
    jComboBoxJam.addItem("18:00 - 19:00");
    jComboBoxJam.addItem("19:00 - 20:00");
    jComboBoxJam.addItem("20:00 - 21:00");

    jComboBoxJam.addItem(jam);

    jComboBoxJam.setSelectedItem(jam);

   
    jTextArea1.setText(keluhan);

    
    try {
        java.util.Date tgl =
            new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tanggal);
        jDateChooser1.setDate(tgl);
    } catch (Exception e) {
        e.printStackTrace();
    }

        }
        
    public void tampilDataTabel(){

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID Booking");
    model.addColumn("Nama Toko");
    model.addColumn("Tanggal");
    model.addColumn("Jam");
    model.addColumn("Keluhan");

    try{

        Connection conn = KoneksiDB.getConnection();

        String sql =
        "SELECT b.id_booking,t.nama,b.tanggal_booking,b.jam_booking,b.keluhan " +
        "FROM booking b " +
        "JOIN tempat t ON b.id_tempat=t.id_tempat";

        PreparedStatement pst = conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        while(rs.next()){

            model.addRow(new Object[]{

                rs.getInt("id_booking"),
                rs.getString("nama"),
                rs.getDate("tanggal_booking"),
                rs.getString("jam_booking"),
                rs.getString("keluhan")

            });

        }

        jTable1.setModel(model);
        

    }catch(Exception e){

        javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxJam = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 675));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nama Toko");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Layanan / Barang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setText("lb1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel5.setText("lb2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel6.setText("lb3");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel7.setText("Nama Toko Yang Terpilih");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 300, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("ID Booking");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Tanggal Booking");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Jam Booking");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("( isi otomatis)");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 110, 40));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 210, 40));

        jButton1.setText("            ");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 343, 90, 30));

        jButton2.setText("               ");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 336, 100, 40));

        jButton3.setText("                   ");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 336, 120, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Keluhan /Deskripsi");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 196, 530, 130));

        jButton4.setText("<");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 60, 70, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Booking", "Nama Toko", "Tanggal", "Jam", "Keluhan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 1160, 230));

        jComboBoxJam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxJam.addActionListener(this::jComboBoxJamActionPerformed);
        jPanel1.add(jComboBoxJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambarBooking.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(1200, 675));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Toko tk = new Toko(1);
        tk.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    try{

        Connection conn = KoneksiDB.getConnection();

        
        String sqlCari = "SELECT id_tempat FROM tempat WHERE nama=?";

        PreparedStatement pstCari = conn.prepareStatement(sqlCari);
        pstCari.setString(1, jLabel7.getText());

        ResultSet rs = pstCari.executeQuery();

        int idTempat = 0;

        if(rs.next()){
            idTempat = rs.getInt("id_tempat");
        }

        String sql = "INSERT INTO booking(id_user,id_tempat,tanggal_booking,jam_booking,keluhan) VALUES(?,?,?,?,?)";

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setInt(1,1); 
        pst.setInt(2,idTempat);
        pst.setDate(3,new java.sql.Date(jDateChooser1.getDate().getTime()));
        pst.setString(4, jComboBoxJam.getSelectedItem().toString());
        pst.setString(5,jTextArea1.getText());

        pst.executeUpdate();
        
        PreparedStatement pstId =
        conn.prepareStatement("SELECT MAX(id_booking) AS id FROM booking");

        ResultSet rsId = pstId.executeQuery();

        if(rsId.next()){
            jLabel11.setText(rsId.getString("id"));
        }

        javax.swing.JOptionPane.showMessageDialog(this,"Booking berhasil");

        tampilDataTabel();
        jLabel11.setText("");
        jTextArea1.setText("");
        jDateChooser1.setDate(null);

        if(jComboBoxJam.getItemCount()>0){
            jComboBoxJam.setSelectedIndex(0);
        }

        idBookingTerpilih = 0;

    }catch(Exception e){

        javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());

    }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if(idBookingTerpilih == 0){
        javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih data pada tabel terlebih dahulu!");
        return;
    }    // TODO add your handling code here:
        
    try{

        Connection conn = KoneksiDB.getConnection();

        String sql = "UPDATE booking SET tanggal_booking=?, jam_booking=?, keluhan=? WHERE id_booking=?";

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setDate(1, new java.sql.Date(jDateChooser1.getDate().getTime()));
        pst.setString(2, jComboBoxJam.getSelectedItem().toString());
        pst.setString(3, jTextArea1.getText());
        pst.setInt(4,idBookingTerpilih);

        pst.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(this,"Data berhasil diupdate");

         tampilDataTabel();

    }catch(Exception e){

        javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());

    }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(idBookingTerpilih == 0){
        javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih data pada tabel terlebih dahulu!");
        return;
    }    // TODO add your handling code here:
        
    try{

        Connection conn = KoneksiDB.getConnection();

        String sql = "DELETE FROM booking WHERE id_booking=?";

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setInt(1, idBookingTerpilih);

        pst.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(this,"Data berhasil dihapus");

        tampilDataTabel();

    }catch(Exception e){

        javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());

    }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
int baris = jTable1.getSelectedRow();

idBookingTerpilih = Integer.parseInt(jTable1.getValueAt(baris,0).toString());

jLabel11.setText(jTable1.getValueAt(baris,0).toString());
jLabel7.setText(jTable1.getValueAt(baris,1).toString());

try{
    java.util.Date tgl =
    new java.text.SimpleDateFormat("yyyy-MM-dd")
    .parse(jTable1.getValueAt(baris,2).toString());

    jDateChooser1.setDate(tgl);

}catch(Exception e){}

jComboBoxJam.setSelectedItem(
    jTable1.getValueAt(baris,3).toString()
);

jTextArea1.setText(jTable1.getValueAt(baris,4).toString());   // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBoxJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJamActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxJamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Booking().setVisible(true));
    }
    
    @Override
public void simpanBooking() {
    jButton1ActionPerformed(null);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBoxJam;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
