package jef_puff;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amali
 */
// Alasan: Connection dipakai untuk menghubungkan form login dengan database users.
import java.sql.Connection;
// Alasan: PreparedStatement dipakai untuk menjalankan query login dengan parameter username dan password.
import java.sql.PreparedStatement;
// Alasan: ResultSet dipakai untuk mengecek apakah akun ditemukan di database.
import java.sql.ResultSet;
// Alasan: JOptionPane dipakai untuk menampilkan pesan login berhasil, gagal, atau error.
import javax.swing.JOptionPane;
// Alasan: Class Login adalah form GUI untuk masuk ke aplikasi.
public class Login extends javax.swing.JFrame {
    
    // Alasan: Logger dipakai untuk mencatat error pada form Login.
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    // Alasan: Constructor Login dijalankan saat form login dibuat.
    public Login() {
        // Alasan: Memanggil seluruh komponen GUI login yang dibuat NetBeans.
        initComponents();
        // Alasan: Form login ditampilkan di tengah layar agar user lebih nyaman.
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonLogin2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 675));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonLogin2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLogin2.setText("Login");
        jButtonLogin2.setBorder(null);
        jButtonLogin2.setBorderPainted(false);
        jButtonLogin2.setContentAreaFilled(false);
        jButtonLogin2.setFocusPainted(false);
        jPanel1.add(jButtonLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 40, 50, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setText("Jakarta Electronic Finder");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 410, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        jTextFieldUsername.setText("Masukkan username");
        jTextFieldUsername.setBorder(null);
        jPanel1.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 400, 40));

        jButtonLogin.setBackground(new java.awt.Color(0, 153, 51));
        jButtonLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(this::jButtonLoginActionPerformed);
        jPanel1.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 460, 60));

        jButtonRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(0, 153, 51));
        jButtonRegister.setText("Register di sini");
        jButtonRegister.setBorder(null);
        jButtonRegister.setBorderPainted(false);
        jButtonRegister.setContentAreaFilled(false);
        jButtonRegister.setFocusPainted(false);
        jButtonRegister.addActionListener(this::jButtonRegisterActionPerformed);
        jPanel1.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Belum punya akun ?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 120, -1));

        jPasswordField2.setText("jPasswordField2");
        jPasswordField2.setBorder(null);
        jPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 372, 410, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gGambarLogin.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1322, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
// TODO add your handling code here:
            try {

           // Alasan: Mengambil koneksi database untuk memeriksa username dan password.
           Connection conn = KoneksiDB.getConnection();

           // Alasan: Query ini mencari user yang username dan password-nya sesuai dengan input login.
           String sql = "SELECT * FROM users WHERE username=? AND password=?";
            // Alasan: Query login disiapkan agar parameter bisa diisi dengan aman.
            PreparedStatement pst = conn.prepareStatement(sql);

            // Alasan: Parameter pertama diisi dengan username dari text field.
            pst.setString(1, jTextFieldUsername.getText());
            // Alasan: Parameter kedua diisi dengan password dari password field.
            pst.setString(2, String.valueOf(jPasswordField2.getPassword()));

            // Alasan: Query SELECT dijalankan dan hasilnya disimpan di ResultSet.
            ResultSet rs = pst.executeQuery();
            
            // Alasan: Jika ResultSet punya data, berarti username dan password benar.
            if (rs.next()) {

                // Alasan: Pesan berhasil ditampilkan agar user tahu login sukses.
                JOptionPane.showMessageDialog(this, "Login Berhasil");

                // Alasan: Objek Customer dibuat sebagai bentuk penggunaan superclass Pengguna dan subclass Customer.
                Pengguna p = new Customer(jTextFieldUsername.getText());

                // Alasan: instanceof mengecek apakah objek Pengguna sebenarnya adalah Customer sebelum casting.
                if (p instanceof Customer) {
                    // Alasan: Casting mengubah referensi Pengguna menjadi Customer agar method Customer bisa dipakai.
                    Customer c = (Customer) p;
                    // Alasan: Method Customer dipanggil untuk menunjukkan penerapan overriding.
                    c.tampilData();
                }

                // Alasan: Jika login berhasil, form Menu dibuka.
                new Menu().setVisible(true);
                // Alasan: Form login ditutup agar tidak menumpuk setelah pindah ke Menu.
                this.dispose();

            // Alasan: Bagian else dijalankan ketika akun tidak ditemukan di database.
            }else {

                // Alasan: Pesan gagal login ditampilkan jika input tidak cocok dengan database.
                JOptionPane.showMessageDialog(this, "Username atau Password Salah");

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());

        }

    }//GEN-LAST:event_jButtonLoginActionPerformed
// Alasan : Event ini berjalan saat user memilih pindah ke halaman Register
    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
// TODO add your handling code here:
        // Alasan: Objek form Register dibuat agar halaman pendaftaran bisa dibuka.
        Register rg = new Register();
        // Alasan: Form Register ditampilkan ke layar.
        rg.setVisible(true);
    }//GEN-LAST:event_jButtonRegisterActionPerformed
    /**
     * @param args the command line arguments
     */
    // Alasan: Method main dipakai untuk menjalankan form Login secara langsung.
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // Alasan: Form Login dijalankan di EventQueue agar GUI Swing berjalan stabil.
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLogin2;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
