package jef_puff;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amali
 */
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
      
        initComponents();
        
        setLocationRelativeTo(null);
                
        setSize(1200, 675);   
        setResizable(false);
        setLocationRelativeTo(null);
        
        jCBWilayahJakarta.removeAllItems();

        jCBWilayahJakarta.addItem("-- Pilih Wilayah Jakarta --");
        jCBWilayahJakarta.addItem("Jakarta Timur");
        jCBWilayahJakarta.addItem("Jakarta Barat");
        jCBWilayahJakarta.addItem("Jakarta Selatan");
        jCBWilayahJakarta.addItem("Jakarta Pusat");
        jCBWilayahJakarta.addItem("Jakarta Utara");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jCBWilayahJakarta = new javax.swing.JComboBox<>();
        jButtonPilih = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 675));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 675));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBWilayahJakarta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBWilayahJakarta.setBorder(null);
        jPanel2.add(jCBWilayahJakarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 430, 50));

        jButtonPilih.setBackground(new java.awt.Color(0, 153, 51));
        jButtonPilih.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonPilih.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPilih.setText("Pilih");
        jButtonPilih.addActionListener(this::jButtonPilihActionPerformed);
        jPanel2.add(jButtonPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 450, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Temukan Teknisi dan Toko Elektronik Terpercaya Di Jakarta");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 340, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel3.setText("Solusi Tepat Untuk ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 340, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Elektronik");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel5.setText("Anda");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jLabel6.setText("berdasarkan rating, ulasan, dan lokasi terdekat.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel7.setText("Perbaikan dan Belanja");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 370, 50));

        jLabel8.setText("Cari tempat servis dan toko elektronik bekas terbaik");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Cara Kerja");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, -1, -1));

        jLabel10.setText("Mudah menemukan layanan elektronik yang anda butuhkan dlam 3 langkah");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Wilayah Jakarta");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 140, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("1. Cari");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, -1, -1));

        jLabel14.setText("Pilih wilayah untuk melihat");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, -1, 20));

        jLabel15.setText("layanan di sekitar Anda");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("2. Pilih");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, -1, -1));

        jLabel17.setText("Lihat rating dan ukuran ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, -1, -1));

        jLabel18.setText("laly pilih tempat terbaik");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("3. Kunjungi");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, -1, -1));

        jLabel20.setText("Hubungi atau kunjungi tempat ");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, -1, -1));

        jLabel21.setText("pilihan Anda");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, -1, -1));

        jButtonLogin.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.setBorder(null);
        jButtonLogin.setBorderPainted(false);
        jButtonLogin.setContentAreaFilled(false);
        jButtonLogin.setFocusPainted(false);
        jButtonLogin.addActionListener(this::jButtonLoginActionPerformed);
        jPanel2.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 40, 40, 30));

        jLabel2.setBackground(new java.awt.Color(0, 153, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarMenu.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1200, 675));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -140, 1680, 950));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 1690, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilihActionPerformed
        // TODO add your handling code here:
        String wilayah = jCBWilayahJakarta.getSelectedItem().toString();

    if (wilayah.equals("-- Pilih Wilayah Jakarta --")) {
   JOptionPane.showMessageDialog(this,
        "Silakan pilih wilayah terlebih dahulu.");
        return;
    }

    if (wilayah.equals("Jakarta Barat")) {
        new WilayahJakarta().setVisible(true);
    }
    else if (wilayah.equals("Jakarta Timur")) {
        new WilayahJakarta().setVisible(true);
    }
    else if (wilayah.equals("Jakarta Selatan")) {
        new WilayahJakarta().setVisible(true);
    }
    else if (wilayah.equals("Jakarta Pusat")) {
        new WilayahJakarta().setVisible(true);
    }
    else if (wilayah.equals("Jakarta Utara")) {
        new WilayahJakarta().setVisible(true);
    }

    dispose();

    }//GEN-LAST:event_jButtonPilihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonPilih;
    private javax.swing.JComboBox<String> jCBWilayahJakarta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
