package jef_puff;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amali
 */
// Alasan: Connection dipakai untuk menghubungkan form Register ke database users.
import java.sql.Connection;
// Alasan: PreparedStatement dipakai untuk menyimpan data akun dengan query berparameter.
import java.sql.PreparedStatement;
// Alasan: JOptionPane dipakai untuk menampilkan validasi dan pesan registrasi.
import javax.swing.JOptionPane;
// Alasan: Class Register adalah form GUI untuk membuat akun baru.
public class Register extends javax.swing.JFrame {
    
    // Alasan: Logger dipakai untuk mencatat error pada form Register.
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    /**
     * Creates new form Register
     */
    // Alasan: Constructor Register dijalankan saat halaman pendaftaran dibuka.
    public Register() {
     
    // Alasan: Ukuran form dikunci agar tampilan register tidak berubah.
    setResizable(false);
    // Alasan: Memanggil komponen GUI register yang dibuat NetBeans.
    initComponents();
    // Alasan: Form Register ditampilkan di tengah layar.
    setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMasukkanNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jTextFieldUsename = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonLogin2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        eye = new javax.swing.JLabel();
        jTextFieldUlangPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Register Akun");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 180, 40));

        jLabel3.setText("Buat akun baru untuk memulai menggunakan Jakarta Electronic Finder");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 380, -1));

        jTextFieldMasukkanNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldMasukkanNama.setText("Masukkan nama lengkap");
        jTextFieldMasukkanNama.setBorder(null);
        jTextFieldMasukkanNama.setPreferredSize(new java.awt.Dimension(169, 23));
        jTextFieldMasukkanNama.addActionListener(this::jTextFieldMasukkanNamaActionPerformed);
        jPanel1.add(jTextFieldMasukkanNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 203, 370, 40));

        jLabel4.setText("Nama Lengkap");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 100, -1));

        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jLabel6.setText(" Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 316, -1, 20));

        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        jLabel8.setText("Konfirmasi Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, -1, -1));

        jButtonRegister.setBackground(new java.awt.Color(0, 153, 51));
        jButtonRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(this::jButtonRegisterActionPerformed);
        jPanel1.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 440, 60));

        jLabel9.setText("Sudah punya akun ?");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 110, 50));

        jButtonLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(0, 153, 51));
        jButtonLogin.setText("Login di sini");
        jButtonLogin.setBorderPainted(false);
        jButtonLogin.setContentAreaFilled(false);
        jButtonLogin.setDefaultCapable(false);
        jButtonLogin.setFocusPainted(false);
        jButtonLogin.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButtonLogin.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButtonLogin.addActionListener(this::jButtonLoginActionPerformed);
        jPanel1.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 110, 30));

        jTextFieldUsename.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldUsename.setText("Masukkan username");
        jTextFieldUsename.setBorder(null);
        jPanel1.add(jTextFieldUsename, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 370, 40));

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldEmail.setText("Masukkan email");
        jTextFieldEmail.setBorder(null);
        jTextFieldEmail.addActionListener(this::jTextFieldEmailActionPerformed);
        jPanel1.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 370, 30));

        jButtonLogin2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLogin2.setText("          ");
        jButtonLogin2.setBorder(null);
        jButtonLogin2.setBorderPainted(false);
        jButtonLogin2.setContentAreaFilled(false);
        jButtonLogin2.setDefaultCapable(false);
        jButtonLogin2.setFocusPainted(false);
        jButtonLogin2.setFocusable(false);
        jButtonLogin2.addActionListener(this::jButtonLogin2ActionPerformed);
        jPanel1.add(jButtonLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 40, 50, 30));

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 406, 350, 30));

        jPasswordField4.setText("jPasswordField4");
        jPasswordField4.setBorder(null);
        jPanel1.add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 340, -1));

        jLabel1.setText("  ");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 416, 20, 20));

        eye.setText("     ");
        eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeMouseClicked(evt);
            }
        });
        jPanel1.add(eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 476, 40, 30));

        jTextFieldUlangPassword.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUlangPassword.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextFieldUlangPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reRegister.jpg"))); // NOI18N
        jTextFieldUlangPassword.setAlignmentX(-50.0F);
        jTextFieldUlangPassword.setAlignmentY(-50.0F);
        jPanel1.add(jTextFieldUlangPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 1719, 850));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Alasan : Event ini berjalan saat user menekan tombol Register.
    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
try {

        // Alasan: Password dari field pertama diubah menjadi String agar bisa dibandingkan dan disimpan.
        String password = String.valueOf(jPasswordField1.getPassword());
        // Alasan: Konfirmasi password diambil untuk memastikan user mengetik password yang sama.
        String konfirmasi = String.valueOf(jPasswordField4.getPassword());

        // Alasan: Validasi ini mengecek apakah ada field yang masih kosong.
        if (jTextFieldMasukkanNama.getText().isEmpty()
                || jTextFieldUsename.getText().isEmpty()
                || jTextFieldEmail.getText().isEmpty()
                || password.isEmpty()
                || konfirmasi.isEmpty()) {

            // Alasan: Pesan ini muncul jika ada data registrasi yang belum diisi.
            JOptionPane.showMessageDialog(this, "Semua data harus diisi!");
            return;
        }

        // Alasan: Validasi ini memastikan password dan konfirmasi password sama.
        if (!password.equals(konfirmasi)) {

        // Alasan: Pesan ini muncul jika password dan konfirmasinya berbeda.
        JOptionPane.showMessageDialog(this, "Password tidak sama!");
        return;

    }
        // Alasan: Mengambil koneksi database untuk menyimpan akun baru.
        Connection conn = KoneksiDB.getConnection();

        // Alasan: Query INSERT dipakai untuk menambahkan akun baru ke tabel users.
        String sql = "INSERT INTO users(username,password,email) VALUES (?,?,?)";

        // Alasan: Query registrasi disiapkan sebelum parameter diisi.
        PreparedStatement pst = conn.prepareStatement(sql);

        // Alasan: Parameter username diisi dari input user.
        pst.setString(1, jTextFieldUsename.getText());
        // Alasan: Parameter password diisi dari password yang sudah diambil.
        pst.setString(2,password);
        // Alasan: Parameter email diisi dari input email user.
        pst.setString(3, jTextFieldEmail.getText());

        // Alasan: executeUpdate menjalankan query INSERT ke database.
        pst.executeUpdate();

        // Alasan: Pesan sukses ditampilkan setelah akun berhasil disimpan.
        JOptionPane.showMessageDialog(this, "Registrasi Berhasil");

        // Alasan: Setelah registrasi berhasil, user diarahkan ke halaman Menu.
        new Menu().setVisible(true);
        // Alasan: Form Register ditutup agar tidak menumpuk.
        this.dispose();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    } // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jButtonLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin2ActionPerformed
// Alasan: Form Login dibuat dan langsung ditampilkan.
        new Login().setVisible(true);
    this.dispose();        // TODO add your handling code here:            
    }//GEN-LAST:event_jButtonLogin2ActionPerformed
// Alasan: Event ini dipakai untuk show/hide password pertama saat label mata diklik.
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
// TODO add your handling code here:
        
    // Alasan: Kondisi ini mengecek apakah password sedang terlihat atau disembunyikan.
    if (jPasswordField1.getEchoChar() == (char)0) {

    // Alasan: Password disembunyikan kembali dengan karakter bullet.
    jPasswordField1.setEchoChar('•');

} else {

    // Alasan: Password dibuat terlihat karena echo character dihapus.
    jPasswordField1.setEchoChar((char)0);

}

    }//GEN-LAST:event_jLabel1MouseClicked
// Alasan: Event ini dipakai untuk show/hide konfirmasi password.
    private void eyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMouseClicked
// TODO add your handling code here:
       
    // Alasan: Kondisi ini mengecek apakah konfirmasi password sedang terlihat atau disembunyikan.
    if (jPasswordField4.getEchoChar() == (char)0) {
        
        // Alasan: Konfirmasi password disembunyikan kembali dengan karakter bullet.
        jPasswordField4.setEchoChar('•');

    } else {

        // Alasan: Konfirmasi password dibuat terlihat karena echo character dihapus.
        jPasswordField4.setEchoChar((char)0);

    

}
        
    }//GEN-LAST:event_eyeMouseClicked
// Alasan: Event ini membuka halaman Login dari link Login di form Register.
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);

    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jTextFieldMasukkanNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMasukkanNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMasukkanNamaActionPerformed
/**
     * @param args the command line arguments
     */
    // Alasan: Method main dipakai untuk menjalankan form Register langsung.
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // Alasan: Form Register dijalankan di EventQueue agar GUI Swing stabil.
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eye;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLogin2;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldMasukkanNama;
    private javax.swing.JLabel jTextFieldUlangPassword;
    private javax.swing.JTextField jTextFieldUsename;
    // End of variables declaration//GEN-END:variables
}
